
insert into book (id,name,isbn,description,category,our_price,list_price)values
('1','Spring Security In Action','9781617297731','Spring Security in Action shows you how to prevent cross-site scripting and request forgery attacks before they do damage. You’ll start with the basics, simulating password upgrades and adding multiple types of authorization.','PROGRAMMING','20.0','28.2'),
('2','Reactive Programming with Reactor','9781789135794','Reactor is an implementation of the Java 9 Reactive Streams specification, an API for asynchronous data processing. This specification is based on a reactive programming paradigm, enabling developers to build enterprise-grade, robust applications with reduced complexity and in less time. ','PROGRAMMING','22.0','29.3'),
('3','Real World Software Development','149196717X','Explore the latest Java-based software development techniques and methodologies through the project-based approach in this practical guide. Unlike books that use abstract examples and lots of theory, Real-World Software Development shows you how to develop several relevant projects while learning best practices along the way.','PROGRAMMING','21.0','30.0'),
('4','Pro Angular 9 Build Powerful and Dynamic Web App','978-1-4842-5998-6','This book is for web developers who want to create rich client-side applications. Foundational knowledge of HTML and JavaScript is recommended.','PROGRAMMING','29.9','25.0'),
('5','TypeScript in 50 lessons',' 978-3-945749-90-6','In “TypeScript in 50 Lessons”, Stefan Baumgartner breaks down the quirks of TypeScript into short, manageable lessons. You’ll make sense of TypeScript concepts, tooling for TypeScript and how to get most out of it without learning a new language. Everything TypeScript explained, from start to finish.','PROGRAMMING','25.8','23.5'),
('6','Progressive WEB Apps with Angular','978-1-4842-4448-7','Harness the power of Angular to build fast, high performance progressive web apps that work offline. Learn exactly how to create an Angular Progressive Web App (PWA) from scratch, how you can use different tools to audit and improve it, and leverage Angular CLI or Workbox to turn your app into a PWA.','PROGRAMMING','23.9','23.0'),
('7','Learn Microservices with Spring Boot','978-1-4842-6131-6','Build Java-based microservices architecture using the Spring Boot framework by evolving an application from a small monolith to an event-driven architecture composed of several services. This revised book follows an incremental approach in teaching the structure of microservices, test-driven development, and common patterns in distributed systems such as service discovery, load balancing, routing, centralized logs, per-environment configuration, and containerization.','PROGRAMMING','22.0','24.9'),
('8','Essential TypeScript','978-1-4842-4979-6','Work with Typescript and get the most from this versatile open source language. Author Adam Freeman begins this book by describing Typescript and the benefits it offers, and goes on to show you how to use TypeScript in realistic scenarios, going in-depth to give you the knowledge you need. ','PROGRAMMING','20.0','22.5'),
('9','Getting Started With Angular','11263471','Learn how to get started using Angular to develop web applications. Discover how to structure your Angular applications, make use of RxJs, unit testing and dependency injection to build a real-world application.','PROGRAMMING','20.0','23.5'),
('10','Spring Security 5 for Reactive Application','9781788995979','Security is one of the most vital concerns for any organization. The complexity of an application is compounded when you need to integrate security with existing code, new technology, and other frameworks. This book will show you how to effectively write Java code that is robust and easy to maintain.','PROGRAMMING','22.5','23.0'),
('11','Spring MVC 2nd Edition','9781785880636','Spring MVC helps you build flexible and loosely coupled web applications. The Spring MVC Framework is architected and designed in such a way that every piece of logic and functionality is highly configurable. Also, Spring can integrate effortlessly with other popular web frameworks such as Struts, WebWork, Java Server Faces, and Tapestry.','PROGRAMMING','21.0','22.0'),
('12','Learning Angular 3rd Edition','9781839210662','Angular, loved by millions of web developers around the world, continues to be one of the top JavaScript frameworks thanks to its regular updates and new features that enable fast, cross-platform, and secure frontend web development. With Angular, you can achieve high performance using the latest web techniques and extensive integration with web tools and integrated development environments (IDEs).','PROGRAMMING','20.0','21.0'),
('13','A Many-Splendoured Thing','9997546822','A Many-Splendoured Thing tells the story of a married British foreign correspondent called Mark Elliot (Ian Morrison in real life and based in Singapore where he lived with his wife and children) who falls in love with a Eurasian doctor originally from Mainland China who trained at the Royal Free Hospital Medical College in London University, only to encounter prejudice from her family and from Hong Kong society.','NOVEL','28.0','30.0'),
('14','Spring Microservices in Action, Second Edition','978-1617293986','Spring Microservices in Action, Second Edition teaches you to build microservice-based applications using Java and Spring. You’ll start by creating basic services, then move to efficient logging and monitoring. Learn to refactor Java applications with Spring’s intuitive tooling, and master API management with Spring Cloud Gateway. You’ll even deploy Spring Cloud applications with AWS and Kubernetes.','PROGRAMMING','20.0','24.0');

